/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Srami
 */
public class MostrarDatosrecepcionista extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEliminarDatos
     */
    DefaultTableModel diseño=new DefaultTableModel();
    Conexion cc = new Conexion();
    
    
    
    public void Listar() {
        LimpiaTabla();
        Connection con = null;
        PreparedStatement pst = null;
        Statement s =null; 
        ResultSet rs = null;
        String sql = "SELECT * FROM equipaje";
        try {
            con = cc.realizarConexion();
            s = con.createStatement();
            rs = s.executeQuery(sql);
            Object[] equipaje = new Object[5];
            diseño = (DefaultTableModel) tabla.getModel();
            while (rs.next()) {

                equipaje[0] = rs.getString("idpasajero");
                equipaje[1] = rs.getString("nombre");
                equipaje[2] = rs.getString("vuelo");
                equipaje[3] = rs.getString("idequipaje");
                equipaje[4] = rs.getString("peso");

                diseño.addRow(equipaje);
            }
            tabla.setModel(diseño);
        } catch (SQLException e) {
        }
    }

    public void LimpiaTabla() {
        for (int i = diseño.getRowCount() - 1; i >= 0; i--) {
            diseño.removeRow(i);
        }
    }
    
    public MostrarDatosrecepcionista() {
        initComponents();
        String[] titulo= new String[]{"IDPASAJERO", "NOMBRE","VUELO", "IDEQUIPAJE", "PESO"};
        diseño.setColumnIdentifiers(titulo);
        tabla.setModel(diseño);
        setLocationRelativeTo(null);
        this.setResizable(false);
        Listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        botonEliminar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 480, 320));

        botonEliminar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonEliminar.setText("Eliminar");
        getContentPane().add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        botonVolver.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wallpaper.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(600, 600));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        dispose();
Menu v= new Menu();
v.setVisible(true);
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
